# Generated by Django 5.2.4 on 2025-07-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
